//------------------------------------------------------------------------------
// <auto-generated> 
// Copyright © Giga Factory 2023
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

class User {
  constructor() {
     this.user_id = ""
     this.nickname = ""
     this.is_leave = 0;
     this.last_login_dt = 0;
     this.created_dt = 0;
     this.dummy_dt = []
}};

class ItemStackable {
  constructor() {
     this.item_id = 0;
     this.count = 0;
}};

class ItemEquip {
  constructor() {
     this.item_id = 0;
     this.grade = 0;
     this.level = 0;
     this.piece_count = 0;
}};

class ItemFloatingPoint {
  constructor() {
     this.item_id = 0;
     this.amount = 0;
}};

