//------------------------------------------------------------------------------
// <auto-generated> 
// Copyright © Giga Factory 2023
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

class AccountLogin {
  constructor(platform_type, platform_id, user_id, device_type, is_leave) {
     this.platform_type = platform_type;
     this.platform_id = platform_id;
     this.user_id = user_id;
     this.device_type = device_type;
     this.is_leave = is_leave;
  }
}

class UserLogin {
  constructor(user, item_floating_point, item_stackable, item_equip) {
     this.user = user;
     this.item_floating_point = item_floating_point;
     this.item_stackable = item_stackable;
     this.item_equip = item_equip;
  }
}


module.exports = {
    AccountLogin,
    UserLogin
}
