//------------------------------------------------------------------------------
// <auto-generated> 
// Copyright © Giga Factory 2023
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

class AccountLogin {
  constructor(platform_type, platform_id) {
     this.platform_type = platform_type;
     this.platform_id = platform_id;
  }
}

class UserLogin {
}

